"""
Curated medication–supplement timing rules for Separation Coach.

Educational only — not a substitute for prescription labels or pharmacist advice.
"""

from __future__ import annotations

from enum import Enum
from typing import Any

# Strength tiers (highest → lowest visibility)
STRENGTH_CRITICAL = "CRITICAL"
STRENGTH_HIGH = "HIGH"
STRENGTH_STANDARD = "STANDARD"

STRENGTH_ORDER = {STRENGTH_CRITICAL: 0, STRENGTH_HIGH: 1, STRENGTH_STANDARD: 2}


class TimeBlock(str, Enum):
    EMPTY_STOMACH = "empty_stomach"
    MORNING = "morning"
    MIDDAY = "midday"
    EVENING = "evening"
    BEDTIME = "bedtime"
    FATTY_MEAL = "fatty_meal"
    FLEXIBLE = "flexible"


TIME_BLOCK_META: dict[str, dict[str, Any]] = {
    TimeBlock.EMPTY_STOMACH.value: {
        "label": "Empty stomach",
        "sort": 0,
        "default_time": "06:30",
        "icon": "🌅",
    },
    TimeBlock.MORNING.value: {
        "label": "Morning",
        "sort": 1,
        "default_time": "08:00",
        "icon": "☕",
    },
    TimeBlock.MIDDAY.value: {
        "label": "Midday",
        "sort": 2,
        "default_time": "12:30",
        "icon": "🌤",
    },
    TimeBlock.EVENING.value: {
        "label": "Evening",
        "sort": 3,
        "default_time": "18:30",
        "icon": "🌆",
    },
    TimeBlock.BEDTIME.value: {
        "label": "Bedtime",
        "sort": 4,
        "default_time": "21:30",
        "icon": "🌙",
    },
    TimeBlock.FATTY_MEAL.value: {
        "label": "With fatty meal",
        "sort": 5,
        "default_time": "18:30",
        "icon": "🥑",
    },
    TimeBlock.FLEXIBLE.value: {
        "label": "Flexible",
        "sort": 6,
        "default_time": "09:00",
        "icon": "📌",
    },
}

BLOCK_SORT = {k: v["sort"] for k, v in TIME_BLOCK_META.items()}

# Curated interaction rules + med-only default timing (empty supp_keywords → med-only)
RULES: list[dict[str, Any]] = [
    # ── Med-only default timing (add Rx chips alone to get a real day plan) ──
    {
        "id": "warfarin-daily-timing",
        "title": "Warfarin — same time daily",
        "med_keywords": ["warfarin", "coumadin", "jantoven"],
        "supp_keywords": [],
        "med_only": True,
        "strength": STRENGTH_CRITICAL,
        "med_block": TimeBlock.EVENING.value,
        "instruction_med": "Take warfarin at the same time every day; keep vitamin K intake steady.",
    },
    {
        "id": "levothyroxine-morning-timing",
        "title": "Levothyroxine — empty stomach",
        "med_keywords": ["levothyroxine", "synthroid", "levoxyl", "unithroid", "tirosint"],
        "supp_keywords": [],
        "med_only": True,
        "strength": STRENGTH_CRITICAL,
        "med_block": TimeBlock.EMPTY_STOMACH.value,
        "instruction_med": "Take on empty stomach with water; wait 30–60 minutes before breakfast.",
    },
    {
        "id": "atorvastatin-evening-timing",
        "title": "Atorvastatin — evening",
        "med_keywords": ["atorvastatin", "lipitor", "rosuvastatin", "simvastatin", "pravastatin"],
        "supp_keywords": [],
        "med_only": True,
        "strength": STRENGTH_STANDARD,
        "med_block": TimeBlock.BEDTIME.value,
        "instruction_med": "Many statins are taken in the evening — follow your prescription label.",
    },
    {
        "id": "metformin-meal-timing",
        "title": "Metformin — with meals",
        "med_keywords": ["metformin", "glucophage"],
        "supp_keywords": [],
        "med_only": True,
        "strength": STRENGTH_STANDARD,
        "med_block": TimeBlock.EVENING.value,
        "instruction_med": "Take metformin with meals as prescribed.",
    },
    {
        "id": "lisinopril-morning-timing",
        "title": "ACE inhibitor — morning",
        "med_keywords": ["lisinopril", "enalapril", "ramipril", "benazepril"],
        "supp_keywords": [],
        "med_only": True,
        "strength": STRENGTH_STANDARD,
        "med_block": TimeBlock.MORNING.value,
        "instruction_med": "Take at the same time daily; morning is common for blood pressure meds.",
    },
    {
        "id": "omeprazole-morning-timing",
        "title": "PPI — before breakfast",
        "med_keywords": ["omeprazole", "pantoprazole", "esomeprazole", "lansoprazole", "prilosec", "nexium"],
        "supp_keywords": [],
        "med_only": True,
        "strength": STRENGTH_HIGH,
        "med_block": TimeBlock.EMPTY_STOMACH.value,
        "instruction_med": "Take 30–60 minutes before breakfast unless your label says otherwise.",
    },
    {
        "id": "sertraline-morning-timing",
        "title": "Sertraline — morning",
        "med_keywords": ["sertraline", "fluoxetine", "escitalopram", "citalopram", "zoloft", "prozac", "lexapro", "ssri"],
        "supp_keywords": [],
        "med_only": True,
        "strength": STRENGTH_STANDARD,
        "med_block": TimeBlock.MORNING.value,
        "instruction_med": "Take at the same time daily as prescribed (morning or evening — stay consistent).",
    },
    {
        "id": "amlodipine-morning-timing",
        "title": "Amlodipine — morning",
        "med_keywords": ["amlodipine", "norvasc", "nifedipine", "felodipine"],
        "supp_keywords": [],
        "med_only": True,
        "strength": STRENGTH_STANDARD,
        "med_block": TimeBlock.MORNING.value,
        "instruction_med": "Take at the same time daily; many take calcium channel blockers in the morning.",
    },
    {
        "id": "magnesium-midday-timing",
        "title": "Magnesium — midday or bedtime",
        "med_keywords": [],
        "supp_keywords": [
            "magnesium",
            "magnesium glycinate",
            "magnesium citrate",
            "magnesium oxide",
            "magnesium malate",
        ],
        "supp_only": True,
        "strength": STRENGTH_STANDARD,
        "supp_block": TimeBlock.MIDDAY.value,
        "instruction_supp": "Midday or bedtime magnesium is common; keep ~2–4h from thyroid meds, antibiotics, and iron if you take those.",
    },
    # ── Med + supplement interaction rules ──
    {
        "id": "warfarin-vitamin-k",
        "title": "Warfarin ↔ vitamin K — keep intake consistent",
        "med_keywords": ["warfarin", "coumadin", "jantoven"],
        "supp_keywords": ["vitamin k", "vitamin k2", "mk-7", "menaquinone", "greens powder"],
        "strength": STRENGTH_CRITICAL,
        "separation_hours": 0,
        "med_block": TimeBlock.EVENING.value,
        "supp_block": TimeBlock.EVENING.value,
        "instruction_med": "Take warfarin at the same time daily; keep vitamin K intake steady.",
        "instruction_supp": "Do not start/stop or wildly change vitamin K without INR monitoring.",
    },
    {
        "id": "warfarin-omega3",
        "title": "Warfarin ↔ high-dose omega-3",
        "med_keywords": ["warfarin", "coumadin", "blood thinner"],
        "supp_keywords": ["fish oil", "omega-3", "omega 3", "epa", "dha"],
        "strength": STRENGTH_CRITICAL,
        "separation_hours": 0,
        "med_block": TimeBlock.EVENING.value,
        "supp_block": TimeBlock.MORNING.value,
        "instruction_med": "Monitor INR if adding or increasing fish oil.",
        "instruction_supp": "Discuss dose with clinician; high doses may add bleeding risk.",
    },
    {
        "id": "thyroid-minerals",
        "title": "Thyroid ↔ minerals",
        "med_keywords": ["levothyroxine", "synthroid", "levoxyl", "unithroid", "tirosint", "thyroid"],
        "supp_keywords": ["calcium", "iron", "ferrous", "magnesium", "zinc", "antacid", "multivitamin"],
        "strength": STRENGTH_CRITICAL,
        "separation_hours": 4,
        "med_block": TimeBlock.EMPTY_STOMACH.value,
        "supp_block": TimeBlock.EVENING.value,
        "instruction_med": "Take on empty stomach with water; wait before food.",
        "instruction_supp": "Separate calcium/iron/magnesium/zinc by at least 4 hours.",
    },
    {
        "id": "bisphosphonate",
        "title": "Bisphosphonate — strict empty stomach",
        "med_keywords": ["alendronate", "fosamax", "risedronate", "actonel", "ibandronate", "boniva"],
        "supp_keywords": [],
        "med_only": True,
        "annotate_all_supplements": True,
        "strength": STRENGTH_CRITICAL,
        "separation_hours": 0,
        "med_block": TimeBlock.EMPTY_STOMACH.value,
        "supp_block": TimeBlock.MORNING.value,
        "instruction_med": "Plain water only; stay upright; follow label before food/other meds.",
        "instruction_supp": "Delay all supplements until your prescription window passes.",
    },
    {
        "id": "statin-grapefruit",
        "title": "Statin ↔ grapefruit",
        "med_keywords": ["simvastatin", "lovastatin", "atorvastatin", "lipitor", "zocor"],
        "supp_keywords": ["grapefruit", "grapefruit juice"],
        "strength": STRENGTH_HIGH,
        "separation_hours": 0,
        "med_block": TimeBlock.BEDTIME.value,
        "supp_block": TimeBlock.FLEXIBLE.value,
        "instruction_med": "Many statins are taken in the evening.",
        "instruction_supp": "Avoid grapefruit with simvastatin/lovastatin unless approved.",
    },
    {
        "id": "statin-coq10",
        "title": "Statin + CoQ10",
        "med_keywords": ["atorvastatin", "rosuvastatin", "simvastatin", "pravastatin", "statin"],
        "supp_keywords": ["coq10", "coenzyme q10", "ubiquinol", "ubiquinone"],
        "strength": STRENGTH_STANDARD,
        "separation_hours": 0,
        "med_block": TimeBlock.BEDTIME.value,
        "supp_block": TimeBlock.FATTY_MEAL.value,
        "instruction_med": "Take statin as directed (often evening).",
        "instruction_supp": "CoQ10 absorbs better with food containing fat.",
    },
    {
        "id": "metformin-b12",
        "title": "Metformin + B12",
        "med_keywords": ["metformin", "glucophage"],
        "supp_keywords": ["vitamin b12", "b12", "methylcobalamin", "cyanocobalamin", "cobalamin"],
        "strength": STRENGTH_STANDARD,
        "separation_hours": 0,
        "med_block": TimeBlock.EVENING.value,
        "supp_block": TimeBlock.MORNING.value,
        "instruction_med": "Take metformin with meals as prescribed.",
        "instruction_supp": "B12 daily is common; ask about labs at annual visits.",
    },
    {
        "id": "quinolone-minerals",
        "title": "Fluoroquinolone ↔ minerals",
        "med_keywords": ["ciprofloxacin", "levofloxacin", "moxifloxacin", "cipro", "levaquin"],
        "supp_keywords": ["calcium", "magnesium", "iron", "zinc", "antacid"],
        "strength": STRENGTH_HIGH,
        "separation_hours": 2,
        "med_block": TimeBlock.MORNING.value,
        "supp_block": TimeBlock.BEDTIME.value,
        "instruction_med": "Take antibiotic per label (often away from minerals).",
        "instruction_supp": "Often 2 h before or 6 h after minerals — confirm on pharmacy label.",
    },
    {
        "id": "tetracycline-minerals",
        "title": "Tetracycline ↔ minerals / dairy",
        "med_keywords": ["doxycycline", "tetracycline", "minocycline"],
        "supp_keywords": ["calcium", "magnesium", "iron", "zinc", "dairy"],
        "strength": STRENGTH_HIGH,
        "separation_hours": 2,
        "med_block": TimeBlock.MORNING.value,
        "supp_block": TimeBlock.BEDTIME.value,
        "instruction_med": "Take with full glass of water unless directed otherwise.",
        "instruction_supp": "Separate minerals and dairy per your antibiotic label.",
    },
    {
        "id": "ppi-iron",
        "title": "Acid reducer ↔ iron",
        "med_keywords": ["omeprazole", "pantoprazole", "esomeprazole", "lansoprazole", "prilosec", "nexium"],
        "supp_keywords": ["iron", "ferrous", "ferrous sulfate", "ferrous gluconate"],
        "strength": STRENGTH_HIGH,
        "separation_hours": 2,
        "med_block": TimeBlock.MORNING.value,
        "supp_block": TimeBlock.EVENING.value,
        "instruction_med": "Take PPI before breakfast if that is how it was prescribed.",
        "instruction_supp": "Iron may absorb better away from morning PPI — ask your pharmacist.",
    },
    {
        "id": "levodopa-protein",
        "title": "Levodopa ↔ protein supplements",
        "med_keywords": ["carbidopa", "levodopa", "sinemet", "rytary"],
        "supp_keywords": ["protein", "whey", "bcaa", "amino acid"],
        "strength": STRENGTH_HIGH,
        "separation_hours": 1,
        "med_block": TimeBlock.EMPTY_STOMACH.value,
        "supp_block": TimeBlock.EVENING.value,
        "instruction_med": "Take levodopa on empty stomach unless your neurologist says otherwise.",
        "instruction_supp": "Keep protein shakes away from dose times.",
    },
    {
        "id": "fiber-meds",
        "title": "Fiber ↔ other medications",
        "med_keywords": ["levothyroxine", "metformin", "lisinopril", "warfarin", "amlodipine"],
        "supp_keywords": ["psyllium", "fiber", "methylcellulose", "benefiber", "inulin"],
        "strength": STRENGTH_STANDARD,
        "separation_hours": 2,
        "med_block": TimeBlock.EMPTY_STOMACH.value,
        "supp_block": TimeBlock.MIDDAY.value,
        "instruction_med": "Take other meds first if separated from bulk fiber.",
        "instruction_supp": "Take fiber at least 2 hours before or after other medications.",
    },
    {
        "id": "magnesium-statin-timing",
        "title": "Magnesium timing with evening meds",
        "med_keywords": ["statin", "atorvastatin", "rosuvastatin"],
        "supp_keywords": ["magnesium", "magnesium glycinate", "magnesium citrate"],
        "strength": STRENGTH_STANDARD,
        "separation_hours": 2,
        "med_block": TimeBlock.BEDTIME.value,
        "supp_block": TimeBlock.MIDDAY.value,
        "instruction_med": "Evening statin as prescribed.",
        "instruction_supp": "Midday magnesium avoids piling everything at bedtime.",
    },
    {
        "id": "ssri-st-johns",
        "title": "Antidepressant ↔ St. John's Wort",
        "med_keywords": ["ssri", "sertraline", "fluoxetine", "escitalopram", "zoloft", "prozac", "lexapro"],
        "supp_keywords": ["st. john's wort", "st johns wort", "hypericum"],
        "strength": STRENGTH_CRITICAL,
        "separation_hours": 0,
        "med_block": TimeBlock.MORNING.value,
        "supp_block": TimeBlock.FLEXIBLE.value,
        "instruction_med": "Take antidepressant as prescribed.",
        "instruction_supp": "Do not combine with St. John's Wort without medical guidance.",
    },
    {
        "id": "surgery-blood-thinners",
        "title": "Pre-surgery supplement disclosure",
        "med_keywords": ["surgery", "pre-op", "warfarin", "aspirin", "clopidogrel", "apixaban"],
        "supp_keywords": ["fish oil", "omega-3", "vitamin e", "garlic", "ginkgo", "ginseng", "turmeric", "curcumin"],
        "strength": STRENGTH_CRITICAL,
        "separation_hours": 0,
        "med_block": TimeBlock.FLEXIBLE.value,
        "supp_block": TimeBlock.FLEXIBLE.value,
        "instruction_med": "Follow surgical team instructions on all prescriptions.",
        "instruction_supp": "Many surgeons ask to stop blood-thinning supplements ~2 weeks before procedures.",
    },
    # ── Supplement-only timing (added for coach self-test / fat-soluble defaults) ──
    {
        "id": "vitamin-d-fatty-meal",
        "title": "Vitamin D — with a meal containing fat",
        "med_keywords": [],
        "supp_keywords": [
            "vitamin d",
            "vitamin d3",
            "vitamin d-3",
            "d3",
            "cholecalciferol",
            "ergocalciferol",
            "vitamins d and k",
        ],
        "supp_only": True,
        "strength": STRENGTH_STANDARD,
        "supp_block": TimeBlock.FATTY_MEAL.value,
        "instruction_supp": "Vitamin D is fat-soluble — take with a meal that includes some fat for absorption.",
    },
    {
        "id": "omega-3-fatty-meal",
        "title": "Omega-3 / fish oil — with food",
        "med_keywords": [],
        "supp_keywords": [
            "fish oil",
            "omega-3",
            "omega 3",
            "epa",
            "dha",
            "cod liver oil",
            "krill oil",
        ],
        "supp_only": True,
        "strength": STRENGTH_STANDARD,
        "supp_block": TimeBlock.FATTY_MEAL.value,
        "instruction_supp": "Take with food to reduce fishy aftertaste and support absorption.",
    },
    {
        "id": "magnesium-bedtime-preference",
        "title": "Magnesium — bedtime",
        "med_keywords": [],
        "supp_keywords": [
            "magnesium",
            "magnesium glycinate",
            "magnesium citrate",
            "magnesium oxide",
            "magnesium malate",
        ],
        "supp_only": True,
        "strength": STRENGTH_STANDARD,
        "supp_block": TimeBlock.BEDTIME.value,
        "instruction_supp": "Bedtime magnesium is common and may support sleep — separate from thyroid meds by several hours if applicable.",
    },
    {
        "id": "vitamin-b-complex-morning",
        "title": "B vitamins — morning",
        "med_keywords": [],
        "supp_keywords": ["vitamin b", "b complex", "b-complex", "b12", "methylcobalamin", "riboflavin", "niacin", "thiamine"],
        "supp_only": True,
        "strength": STRENGTH_STANDARD,
        "supp_block": TimeBlock.MORNING.value,
        "instruction_supp": "B vitamins are often taken in the morning with breakfast.",
    },
    {
        "id": "vitamin-c-morning",
        "title": "Vitamin C — morning",
        "med_keywords": [],
        "supp_keywords": ["vitamin c", "ascorbic acid", "ester-c"],
        "supp_only": True,
        "strength": STRENGTH_STANDARD,
        "supp_block": TimeBlock.MORNING.value,
        "instruction_supp": "Vitamin C is commonly taken in the morning; split from iron by several hours if you take both.",
    },
    {
        "id": "ginseng-midday",
        "title": "Ginseng — midday",
        "med_keywords": [],
        "supp_keywords": ["ginseng", "panax", "eleuthero", "siberian ginseng"],
        "supp_only": True,
        "strength": STRENGTH_STANDARD,
        "supp_block": TimeBlock.MIDDAY.value,
        "instruction_supp": "Ginseng is often taken earlier in the day — avoid late evening if it affects your sleep.",
    },
    {
        "id": "biotin-morning",
        "title": "Biotin — morning",
        "med_keywords": [],
        "supp_keywords": ["biotin"],
        "supp_only": True,
        "strength": STRENGTH_STANDARD,
        "supp_block": TimeBlock.MORNING.value,
        "instruction_supp": "Biotin is typically taken with breakfast.",
    },
    {
        "id": "iron-empty-stomach",
        "title": "Iron — empty stomach",
        "med_keywords": [],
        "supp_keywords": ["iron", "ferrous", "ferrous sulfate", "ferrous gluconate", "iron bisglycinate"],
        "supp_only": True,
        "strength": STRENGTH_STANDARD,
        "supp_block": TimeBlock.EMPTY_STOMACH.value,
        "instruction_supp": "Iron often absorbs best on an empty stomach unless your label says with food.",
    },
    {
        "id": "zinc-morning",
        "title": "Zinc — morning",
        "med_keywords": [],
        "supp_keywords": ["zinc", "zinc picolinate", "zinc gluconate", "zinc citrate"],
        "supp_only": True,
        "strength": STRENGTH_STANDARD,
        "supp_block": TimeBlock.MORNING.value,
        "instruction_supp": "Take zinc away from iron and calcium by several hours.",
    },
    {
        "id": "melatonin-bedtime",
        "title": "Melatonin — bedtime",
        "med_keywords": [],
        "supp_keywords": ["melatonin"],
        "supp_only": True,
        "strength": STRENGTH_STANDARD,
        "supp_block": TimeBlock.BEDTIME.value,
        "instruction_supp": "Take melatonin 30–60 minutes before bed.",
    },
    {
        "id": "5-htp-bedtime",
        "title": "5-HTP — bedtime",
        "med_keywords": [],
        "supp_keywords": ["5-htp", "5 htp", "hydroxytryptophan"],
        "supp_only": True,
        "strength": STRENGTH_STANDARD,
        "supp_block": TimeBlock.BEDTIME.value,
        "instruction_supp": "Often taken at night; do not combine with antidepressants without medical guidance.",
    },
    {
        "id": "curcumin-fatty-meal",
        "title": "Curcumin / turmeric — with food",
        "med_keywords": [],
        "supp_keywords": ["curcumin", "turmeric", "curcuma"],
        "supp_only": True,
        "strength": STRENGTH_STANDARD,
        "supp_block": TimeBlock.FATTY_MEAL.value,
        "instruction_supp": "Curcumin absorbs better with a meal containing fat and often black pepper (piperine).",
    },
]
